language: cpp
dist: bionic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - libssl1.1
      - cmake-data
env:
- MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
- eval ${MATRIX_EVAL}

install:
- travis_retry wget https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.6.2.tar.gz
- tar zxvf yaml-cpp-0.6.2.tar.gz
- cd yaml-cpp-yaml-cpp-0.6.2
- mkdir build
- cd build
- cmake .. && cmake --build . && sudo env "PATH=$PATH" cmake --build . --target install

script:
- pushd log4cplus
- autoreconf -f
- popd
- mkdir Debug && cd Debug && cmake .. && cmake --build . && ctest
